name: Tests
on: [pull_request, push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Run Tests
        run: ./gradlew test